# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:

- powershell: git checkout yaml
  displayName: Fix detached head
-  task: DotNetCoreCLI@2
   displayName: Build solution

- powershell: |
   Get-ChildItem -Recurse
  displayName: Show me what's here

- powershell: |
   echo $(Build.BuildNumber) > version.txt
  displayName: Update Version
- powershell: |
    git config --global user.email "yoavklein25@gmail.com"
    git config --global user.name "yoav-klein"
    git add .
    git commit -m "Build number $(Build.BuildNumber)"
    git push https://625a87a4570f58a6605f2033f1cd0f15ff1c143f@github.com/yoav-klein/csharp-tutorial.git
  displayName: 'Push to Git'
